### PR TITLE
Adding ui.json to fix nat support

### PR DESCRIPTION
**Pull request by MiwiDots**

### CODE REVIEW

**Review by sonicaj — COMMENTED** [review]
This would be true for all branches i.e 11.2/11.3/master. Do we want this to be there for them ?

**Comment by sonicaj** [comment]
If user fetches this plugin in 11.2, iocage will try to find 11.2-RELEASE branch for this plugin, if not found, it will use master then

**Comment by MiwiDots** [comment]
The default port is for this plugin 4242 the ui.json was just never added.

**Comment by sonicaj** [comment]
Just to be clear, so this change is intended for 11.2 users as well ? Like they should be able to see this admin portal ?

**Comment by MiwiDots** [comment]
> Just to be clear, so this change is intended for 11.2 users as well ? Like they should be able to see this admin portal ?

No because it was always 4242 even now for 11.1 and 11.2 users. It was never added but now for nat support we need this up :-)

**Review by sonicaj — APPROVED** [review]
Thank you for clarifying

**Pull request merged**
